name: photoaday
description: A dating app
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.3.0
  # google_mlkit_face_detection: ^0.5.0 # https://issuetracker.google.com/issues/254418199
  flutter_device_type: ^0.4.0
  cupertino_icons: ^1.0.5
  flutter_statusbarcolor_ns: ^0.5.0
  shared_preferences: ^2.0.15
  email_validator: ^2.1.17
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  string_validator: ^0.3.0
  json_annotation: ^4.7.0
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.5
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.2.0
  crypto: ^3.0.2
  # font_awesome_flutter: 10.1.0
  # google_fonts: 3.0.1
  # provider: 6.0.3
  # rxdart: 0.27.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  system_theme: ^2.0.0
  photo_view: ^0.14.0
  provider: ^6.0.4
  flutter_lints: ^2.0.1

  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/
  #   - assets/covers/
  #   - assets/congrats.gif
